dataset_label: nih
n_topics: 150
max_iter: 25
anchors:
  # The infection topic space is busy, so split into: {covid, viral, bacterial, parasitic}
  - ['infection', 'covid', "coronavirus", 'covid_19', '2019_ncov', 'sars_cov_2']
  - ["infection", "hiv"]
  - ["infection", "bacteria"]
  - ["infection", "parasite"]
metadata:
  entity_type: 'projects'
  funding_currency: '$'
